#' Simulate average unfished biomass using lognormal recruitment
#'
#' This function simulates the average unfished biomass of herring using a
#' lognormal recruitment strategy and data including
#' weight-at-age, proportion of stock that are mature, and a constant survival
#' rate.
#'
#' Recruitment is treated as a quasi-spawner-independent process. The spawner-
#' recruit estimates may or may not be stratified. Within each strata, the mean
#' recruitment multiplied by a log-normal error, where the variance term is
#' computed from the data within each strata.
#'
#' @param N_t initial data frame of herring numbers-at-age.
#' Generated by [B_sim_init()]
#' @param recruits numeric vector of estimates of annual recruits (millions)
#' @param spawners numeric vector of estimates for spawning biomass three years
#' prior (metric tons)
#' @param strata factor vector giving the strata for the empirical spawner-recruit
#' relationship
#' @param mean_wt numeric vector of mean weight-at-age for ages 3 to 8+
#' @param maturity numeric vector of estimated maturity-at-age for ages 3 to 8+
#' @param S estimated constant survival rate for all age classes
#' @param num_years Integer; the number of years to simulate to
#' @return A data frame made up of the following vectors
#' - **YEAR:** Index of simulated year
#' - **B:** Simulated biomass (tons) for that year
#' - **B_cumavg:** The cumulative average biomass (tons) up to that year
#' - **AUB.25:** The estimated 25 percent management threshold for entire series
#' - **AUB:** The estimated average unfished biomass
#'
#' @references \insertRef{methot2011}{herringSim}
#'
#' @export



B_sim_lnRecruitment <- function(N_t, recruits, spawners, strata = NA,
                            mean_wt, maturity, S, num_years = 2500){

  #------------------------------  SET-UP  ------------------------------------#

  # gather spawner-recruit estimates into a data frame

  sr <- data.frame(recruits = recruits,
                   spawners = spawners,
                   strata = as.numeric(strata))

  ## compute biomass for first 8 years

  N_t$B_tonnes <- apply(as.matrix(N_t[,1:6]), MARGIN = 1,
                        FUN = function(x) x %*% as.matrix(mean_wt*maturity))

  # append N_t data frame with NAs to be filled in by simulation

  NAs <- data.frame(matrix(NA, ncol = ncol(N_t), nrow = num_years-5))
  colnames(NAs) <- colnames(N_t)

  N_t <- rbind(N_t, NAs)

  # stratify sr and compute mean and sd recruitment within strata

  if(length(unique(sr$strata)) > 1){

    sr_list <- split_sr(recruits = sr$recruits, spawners = sr$spawners,
                        strata = sr$strata)
    Rbar <- lapply(sr_list, FUN = function(x) mean(x[,"recruits"]))
    sigmahat2 <- lapply(sr_list,
                        FUN = function(x) {
                          fit_intercept(x$recruits, x$spawners,
                                        start = list(logmu = 20, logsigma2 = 5),
                                        errorStructure = "multiplicative")$coef[2]
                              }
                        )
    # note: sigmahat2 in log-space

  } else if(length(unique(sr$strata)) <= 1) {

    Rbar <- mean(sr$recruits)
    sigmahat2 <- fit_intercept(sr$recruits, sr$spawners,
                               start = list(logmu = 20, logsigma2 = 5),
                               errorStructure = "multiplicative")$coef[2]

  }

  #----------------------------  SIMULATION  ----------------------------------#

  for(t in 9:nrow(N_t)){

    # these if statements generalize sampling regime to any number of given strata

    N_t$age3[t] <- R_gen(recruits = sr$recruits, spawners = sr$spawners,
                         strata = sr$strata,
                         Rbar = Rbar, sigmahat2 = sigmahat2,
                         Nt3 = N_t$B_tonnes[t-3])

    # compute biomass of spawning stock
    N_t$B_tonnes[t] <- as.matrix(N_t[t,1:6]) %*% as.matrix(mean_wt*maturity)

    # compute other age classes
    ifelse(t+1<=nrow(N_t), N_t$age4[t+1] <- N_t$age3[t] * S, next)
    ifelse(t+2<=nrow(N_t), N_t$age5[t+2] <- N_t$age4[t+1] * S, next)
    ifelse(t+3<=nrow(N_t), N_t$age6[t+3] <- N_t$age5[t+2] * S, next)
    ifelse(t+4<=nrow(N_t), N_t$age7[t+4] <- N_t$age6[t+3] * S, next)

    # age7 + age8 -> age8 (plus group accounted for)
    ifelse(t+5<=nrow(N_t),
           N_t$age8[t+5] <- (N_t$age7[t+4] + N_t$age8[t+4]) * S,
           next)
  }


  #-------------------------  PROCESS RESULTS  --------------------------------#

  # convert to us tons (1 tonne = 1.102311 ton)

  N_t$B_tons <- N_t$B_tonnes * 1.102311

  # compute cumulative average biomass in tons

  B <- data.frame(YEAR = 1:num_years, B = N_t[-8:-1,"B_tons"])
  # B <- data.frame(YEAR = 1:num_years, B = N_t[-8:-1,"B_tons_total"])
  B$B_cumavg <- cumsum(B$B) / seq_along(B$B)

  # compute AUB / .25*AUB for years after convergence

  year_converges <- find_convergence(B$B_cumavg)

  # compute AUB and threshold after convergence year

  B$AUB <- B$AUB.25 <- NA
  B$AUB[B$YEAR > year_converges] <- mean(B$B[B$YEAR > year_converges])
  # estimated AUB of 80k tons

  aub <- unique(na.omit(B$AUB))
  threshold <- 0.25*aub

  B$AUB.25[B$YEAR > year_converges] <- threshold

  return(B)
}
