#' Simulate average unfished biomass using empirical method
#'
#' This function simulates the average unfished biomass of herring using a
#' user-specified empirical spawner-recruit relationship and data including
#' weight-at-age, proportion of stock that are mature, and a constant survival
#' rate.
#'
#' @param N_t initial data frame of herring numbers-at-age.
#' Generated by [B_sim_init()]
#' @param recruits numeric vector of estimates of annual recruits (millions)
#' @param spawners numeric vector of estimates for spawning biomass three years
#' prior (tonnes)
#' @param strata factor vector giving the strata for the empirical spawner-recruit
#' relationship
#' @param mean_wt numeric vector of mean weight-at-age for ages 3 to 8+
#' @param maturity numeric vector of estimated maturity-at-age for ages 3 to 8+
#' @param S estimated constant survival rate for all age classes
#' @param num_years Integer; the number of years to simulate to
#' @param max_iters Integer; the maximum number of years to simulate before throwing
#' an error if convergence in cumulative mean series is not achieved. Must be
#' greater than `num_years`
#' @return A data frame made up of the following vectors
#' - **YEAR:** Index of simulated year
#' - **B:** Simulated biomass (tons) for that year
#' - **B_cumavg:** The cumulative average biomass (tons) up to that year
#' - **AUB.25:** The estimated 25 percent management threshold for entire series
#' - **AUB:** The estimated average unfished biomass
#'
#' @export



B_sim_empirical <- function(N_t = NULL, recruits, spawners, strata = NA,
                            mean_wt, maturity, S, num_years = 5000,
                            max_iters = 10000){

  #----------------------------  sanity check  --------------------------------#

  if(max_iters < num_years){
    stop("max_iters must be greater than num_years")
  }

  #------------------------------  SET-UP  ------------------------------------#

  # initialize age-matrix if not provided

  if(is.null(N_t)){
    N_t <- B_sim_init(recruits = recruits, S = S)
  }

  # gather spawner-recruit estimates into a data frame

  sr <- data.frame(recruits = recruits,
                   spawners = spawners,
                   strata = strata)

  ## compute biomass for first 8 years and cumulative mean

  N_t$B_tonnes <- apply(as.matrix(N_t[,1:6]), MARGIN = 1,
                        FUN = function(x) x %*% as.matrix(mean_wt*maturity))
  N_t$B_cumavg[!is.na(N_t$B_tonnes)] <- cumsum(na.omit(N_t$B_tonnes)) / seq_along(na.omit(N_t$B_tonnes))


  # stratify sr and compute strata boundaries

  if(length(unique(strata)) > 1){

    sr_list <- split_sr(sr$recruits, sr$spawners, sr$strata)
    splits <- strata_boundaries(sr_list)

  } else if((length(unique(strata)) == 1) | (is.na(strata))){

    sr_list <- list(sr)

  }

  #----------------------------  PRE-SIMULATION  ----------------------------------#

  # this simulation occurs until cumulative average series converges, then
  # the actual simulation from which B0 is calculated will continue for num_years

  convergence <- FALSE
  t <- 9

  while(!convergence){

    # sample recruits based on spawning biomass
    N_t[t,"age3"] <- sample_recruits(SSB = N_t[t-3,"B_tonnes"], sr_list = if(exists("sr_list")) sr_list else sr)

    # compute biomass and cumulative average
    N_t$B_tonnes[t] <- as.matrix(N_t[t,1:6]) %*% as.matrix(mean_wt*maturity)
    N_t$B_cumavg[t] <- weighted.mean(c(N_t$B_cumavg[t-1], N_t$B_tonnes[t]), w = c(t-6, 1))

    # compute other age classes
    N_t[t+5,] <- NA
    N_t$age4[t+1] <- N_t$age3[t] * S
    N_t$age5[t+2] <- N_t$age4[t+1] * S
    N_t$age6[t+3] <- N_t$age5[t+2] * S
    N_t$age7[t+4] <- N_t$age6[t+3] * S

    # age7 + age8 -> age8 (plus group accounted for)
    N_t$age8[t+5] <- (N_t$age7[t+4] + N_t$age8[t+4]) * S

    convergence <- suppressWarnings(find_convergence(na.omit(N_t$B_cumavg)))

    if((t > (max_iters-num_years)) & !convergence){
      stop("convergence failed, try again with new random seed")
    }

    t <- t+1
  }

  #----------------------------  SIMULATION  ----------------------------------#

  # pick up where we left off...

  sim_start <- t

  # append N_t data frame with NAs to be filled in by simulation

  NAs <- data.frame(matrix(NA, ncol = ncol(N_t), nrow = num_years))
  colnames(NAs) <- colnames(N_t)

  N_t <- rbind(N_t, NAs)

  for(t in sim_start:nrow(N_t)){

    # sample recruits based on spawning biomass
    N_t[t,"age3"] <- sample_recruits(SSB = N_t[t-3,"B_tonnes"], sr_list = if(exists("sr_list")) sr_list else sr)

    # compute biomass and cumulative average
    N_t$B_tonnes[t] <- as.matrix(N_t[t,1:6]) %*% as.matrix(mean_wt*maturity)
    N_t$B_cumavg[t] <- weighted.mean(c(N_t$B_cumavg[t-1], N_t$B_tonnes[t]), w = c(t-6, 1))

    # compute other age classes
    ifelse(t+1<=nrow(N_t), N_t$age4[t+1] <- N_t$age3[t] * S, next)
    ifelse(t+2<=nrow(N_t), N_t$age5[t+2] <- N_t$age4[t+1] * S, next)  # ifelse statements ensure that all age
    ifelse(t+3<=nrow(N_t), N_t$age6[t+3] <- N_t$age5[t+2] * S, next)  # classes are filled in at the bottom of
    ifelse(t+4<=nrow(N_t), N_t$age7[t+4] <- N_t$age6[t+3] * S, next)  # of the age matrix

    # age7 + age8 -> age8 (plus group accounted for)
    ifelse(t+5<=nrow(N_t),
           N_t$age8[t+5] <- (N_t$age7[t+4] + N_t$age8[t+4]) * S, next)
  }


  #-------------------------  PROCESS RESULTS  --------------------------------#

  # convert to us tons (1 tonne = 1.102311 ton)

  N_t$B_tons <- N_t$B_tonnes * 1.102311
  N_t$B_cumavg_tons <- N_t$B_cumavg * 1.102311

  # make data frame for simulated biomasses to return

  B <- data.frame(YEAR = 1:(nrow(N_t)-8),
                  B = N_t[-8:-1,"B_tons"],
                  B_cumavg = N_t[-8:-1,"B_cumavg_tons"])

  # compute AUB and threshold after convergence year (last 5000 years of simulation)

  year_converges <- nrow(B) - num_years

  B$AUB <- B$AUB.25 <- NA
  B$AUB[B$YEAR > year_converges] <- mean(B$B[B$YEAR > year_converges])
  aub <- unique(na.omit(B$AUB))
  threshold <- 0.25*aub

  B$AUB.25[B$YEAR > year_converges] <- threshold

  return(B)
}

