#' Sample Recruits
#'
#' This function simulates future herring age-3 recruits by sampling past recruits.
#' Future recruits may be generated from a stratified sample using any number
#' of strata.
#'
#' @param SSB Spawning biomass from which to simulate recruits
#' @param sr_list List of stratafied spawner-recruit data, as generated by
#' [split_sr()]
#'
#' @return A numeric scalar of millions of recruits
#'
#' @export
#'

sample_recruits <- function(SSB, sr_list){

  # calculated strata boundaries

  if(length(sr_list) > 1){
    splits <- strata_boundaries(sr_list)
  }

  # these if statements generalize sampling regime to any number of given strata

  if(length(sr_list) == 1){

    out <- sample(sr_list[[1]][,"recruits"], 1)

  } else if(length(sr_list) == 2){

    # these if statements identifies B[y-3] and sample recruits accordingly

    if(SSB < splits){
      out <- sample(sr_list[[1]][,"recruits"], 1)
    } else if(splits <= SSB){
      out <- sample(sr_list[[2]][,"recruits"], 1)
    }

  } else if(length(sr_list) >= 3){

    if(SSB < splits[1]){
      out <- sample(sr_list[[1]][,"recruits"], 1)
    } else if((splits[1] <= SSB) & (SSB < splits[length(sr_list)-1])){
      for(j in 2:(length(sr_list)-1)){
        if((splits[j-1] <= SSB) & (SSB < splits[j])){
          out <- sample(sr_list[[j]][,"recruits"], 1)
        } else {
          next
        }
      }
    } else if(splits[length(sr_list)-1] <= SSB){
      out <- sample(sr_list[[length(sr_list)]][,"recruits"], 1)
    }
  }
  return(out)
}
